// Code generated by mockery. DO NOT EDIT.
//go:generate mockery --name=WiFiHandle --output=. --filename=WiFiHandle_test.go --inpackage

package wifi_test

import (
	wifilib "github.com/mdlayher/wifi"
	"github.com/stretchr/testify/mock"
)

// WiFiHandle is an autogenerated mock type for the WiFiHandle type.
type WiFiHandle struct {
	mock.Mock
}

// Interfaces provides a mock function with given fields.
func (m *WiFiHandle) Interfaces() ([]*wifilib.Interface, error) {
	ret := m.Called()

	var r0 []*wifilib.Interface
	if rf, ok := ret.Get(0).(func() []*wifilib.Interface); ok {
		r0 = rf()
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]*wifilib.Interface)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockTestingT interface {
	mock.TestingT
	Cleanup(f func())
}

// NewWiFiHandle creates a new instance of WiFiHandle.
// It also registers a testing interface and a cleanup function to assert expectations.
func NewWiFiHandle(t mockTestingT) *WiFiHandle {
	mockObj := &WiFiHandle{}
	mockObj.Mock.Test(t)

	t.Cleanup(func() { mockObj.AssertExpectations(t) })

	return mockObj
}
